config/routes.rb
Winning::Application.routes.draw do

  root 'issues#index'

  get 'login/home' => 'login#home', as: 'login'
  get 'login/github' => 'login#github_login', as: 'github_login'
  get 'login/github/callback' => 'login#github_callback', as: 'github_callback'
  get 'login/pick_a_repo' => 'login#pick_a_repo', as: 'pick_a_repo'
  get 'login/pick_repo' => 'login#pick_repo', as: 'pick_repo'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def setup_octokit_client
    token = session[:github_token]
    fail "You don't have an active GitHub token"  if token.nil?

    @octokit = Octokit::Client.new :access_token => token
    @octokit.user.login
  end

  def require_github_session
    return redirect_to login_url  if session[:github_token].nil?
    setup_octokit_client

    false
  end

  def require_repo_config
    val = require_github_session  
    return val  if val
    return redirect_to pick_a_repo_url  if session[:repo_name].nil?
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController

  before_filter :require_repo_config

  def index
    @repo_name = session[:repo_name]

    repo = @octokit.repo @repo_name
    @issues = repo.rels[:issues].get.data
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def home
  end

  def github_login
    url = 'https://github.com/login/oauth/authorize?scope=user:email,repo&client_id='
    url << ENV['GITHUB_CLIENT_ID']

    redirect_to url
  end

  def github_callback
    code = params['code']
    fail "NO OAuth CODE!"  if code.nil?

    gh_access_token_path = '/login/oauth/access_token'
    gh_authorize_path = '/login/oauth/authorize'

    client = OAuth2::Client.new( ENV['GITHUB_CLIENT_ID'], ENV['GITHUB_CLIENT_SECRET'],
      site: 'https://github.com',
      token_url: gh_access_token_path,
      authorize_path: gh_authorize_path
      )
    token = client.auth_code.get_token(code)
    fail "Failed to get OAuth access token."  if token.nil?

    session[:github_token] = token.token
    redirect_to '/'
  end

  def pick_a_repo
    require_github_session
    @repos = @octokit.user.rels[:repos].get.data
  end

  def pick_repo
    name = params[:repo_name]
    fail "No repo selected!" if name.nil? or name.empty?

    session[:repo_name] = name
    redirect_to '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/issues/index.html.erb
<h1>Let's get Winning!</h1>

<p>Repo: <%= @repo_name %></p>

<h3>Issues</h3>

<ul>
  <% @issues.each do |issue| %>
    <li><%= issue.number %> - <%= issue.title %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Winning</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="header">
    <div class="brand">Winning</div>
  </div>

  <div class="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/login/home.html.erb
<h1>Let's get Winning!</h1>
<p>You've got to login first to see if you're winning.</p>

<%= link_to 'Sign In With Github', github_login_url, class:'pure-button pure-button-primary' %>

app/views/login/pick_a_repo.html.erb
<h2>Pick a Repo</h2>
<p>This is the repo for which you'd like to track issues.</p>

<% @repos.each do |repo| %>

  <div class="repo">
    <%= link_to repo.name, pick_repo_url(repo_name:repo.full_name) %>
  </div>

<% end %>